package topdownshooter.Zombie;

import java.awt.*;
import java.util.Random;

import topdownshooter.Core.ConfigHandler.ZombieProperties;
import topdownshooter.Weapon.Projectiles.AcidSpit;
import topdownshooter.Core.Globals;
import topdownshooter.Core.SpriteAnimation;

public class AcidZombie extends AbstractZombie {
    private final int SPIT_RANGE = 100;

    private Random random;

    public AcidZombie(ZombieProperties properties, int x, int y) {
        super(properties);
        this.x = x;
        this.y = y;
        this.type = ZombieType.ACID;

        this.random = new Random();

        this.spriteAnimation = new SpriteAnimation(Globals.ACID_ZOMBIE_MOVE);
        this.spriteAnimation.setTargetSize(WIDTH, HEIGHT);
    }
    
    public AcidZombie(int x, int y, double r, double health, int speed, int damage, int points, int range, ZombieType type) {
        super(x, y, r, health, speed, damage, points, range, type);

        this.random = new Random();

        this.spriteAnimation = new SpriteAnimation(Globals.ACID_ZOMBIE_MOVE);
        this.spriteAnimation.setTargetSize(WIDTH, HEIGHT);
    }

    @Override
    public void draw(Graphics g) {
        this.spriteAnimation.draw(g, this.x, this.y, this.r);
    }

    public AcidSpit rangedAttack() {
        int val = random.nextInt(Globals.Time2GameTick(1000));
        // there is a probability of 50 percent of ranged attack generated by the zombie
        if (val < Globals.Time2GameTick(100)) {
            double translatedX = this.x + WIDTH / 2 + this.spriteAnimation.getOffset().getX() * Math.cos(this.r) - this.spriteAnimation.getOffset().getY() * Math.sin(this.r);
            double translatedY = this.y + HEIGHT / 2 + this.spriteAnimation.getOffset().getX() * Math.sin(this.r) + this.spriteAnimation.getOffset().getY() * Math.cos(this.r);

            return new AcidSpit((int) translatedX, (int) translatedY, this.r, (int) (this.damage*0.5));  // Ranged attacks only gives half damage
        }
        return null;
    }

    @Override
    public void update(int px, int py) {

        // Take distance between zombie and survivor
        int dx = px - this.x;
        int dy = py - this.y;
        double distance = Math.sqrt(dx * dx + dy * dy);

        // If distance is bigger than spit range, try to catch the player
        if (distance > SPIT_RANGE) {
            if (this.x < px) this.x += this.speed;
            if (this.x > px) this.x -= this.speed;
            if (this.y < py) this.y += this.speed;
            if (this.y > py) this.y -= this.speed;
        } else {

        }       
    }


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("AcidZombie{");
        sb.append("x=" + this.x + ", ");
        sb.append("y=" + this.y + ", ");
        sb.append("r=" + this.r + ", ");
        sb.append("health=" + this.health + ", ");
        sb.append("speed=" + this.speed + ", ");
        sb.append("damage=" + this.damage + ", ");
        sb.append("points=" + this.points + ", ");
        sb.append("range=" + this.range + ", ");
        sb.append("type=" + this.type);
        sb.append("}");

        return sb.toString();
    }
}
