/*
 * This source file was generated by the Gradle 'init' task
 */
package topdownshooter;

public class Game {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new Game().getGreeting());
    }
}
