/*
 * This source file was generated by the Gradle 'init' task
 */
package topdownshooter;

import javax.swing.*;

public class Game {
    public static void main(String[] args) {
        SwingUtilities.invokeLater(() -> {
            JFrame frame = new JFrame("Zombie Shooter");
            frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
            frame.setSize(800, 600);
            frame.setResizable(false);

            MenuPanel menuPanel = new MenuPanel(frame);
            frame.add(menuPanel);
            frame.setVisible(true);
        });
    }
}
