/*
 * This source file was generated by the Gradle 'init' task
 */
package topdownshooter;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class GameTest {
    @Test void appHasAGreeting() {
        //Game classUnderTest = new Game();
        //assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
}
